### ISSUE TITLE
add Put.io download support

### ISSUE THREAD

**Issue by CuddleBear92** [japanesemediamanager/ShokoDesktop#140]
could you add support for the https://put.io/ site?
it has its own api detailed here: https://put.io/v2/docs/index.html

put.io is a torrent seedbox that you can use as a torrent client aswell.
download torrents to the site and it will seed for your closed sites like baka.bt and others aswell as giving the users really fast downloads from the site itself.

i for one think the site is worth the cost as it frees up your line, dont actually downloads torrents so the state cant track your downloads with it aswell as supporting much faster downloads from the site itself on slow torrents.

shared torrents is really nice too IMO, if another user have downloaded a torrent before it will be on their server for a while and will auto complete the download if that is the case (enabling you to direct download at max speed right away no matter how bad the seeds are)

**Comment by ElementalCrisis** [comment]
Similar to #10, going to close all torrent program support issues and make #10 the main issue for it.

**Comment by AreFinstad** [comment]
hmmm false, put.io would not be able to use a blackhole folder the same way at all as its no a local program at all. its a seedbox, more manual work would be needed for such things for it to use those files (adding one torrent file at a time to the site).

i was thinking more like api support to upload or link the torrent file to the site itself without the need for manual work and moving.

**Comment by ElementalCrisis** [comment]
Issue reopened. This is probably something someone else will have to add as the torrent black hole is the solution for now for torrent programs.

**Comment by ElementalCrisis** [comment]
Closing this issue since all torrent functionality has been removed.
