### ISSUE TITLE
Allow multiple Movie DB links for a series.

### ISSUE THREAD

**Issue by CatmanIX** [japanesemediamanager/ShokoDesktop#182]
Probably a rare use-case, but for "series" like Mardock Scramble, which is three movies grouped together on AniDB, but isn't listed on TVDB because it isn't a TV show, it would be nice to associate each movie on MDB with the related "episode" on AniDB so we can get the proper metadata.

**Comment by CatmanIX** [comment]
I guess you could say this is related to issue #66.

**Comment by ElementalCrisis** [comment]
Duplicate of #66.

**Comment by jmediamanager** [comment]
Ignore the Fix above, I put the wrong issue number
