### ISSUE TITLE
set up a transifex page?

### ISSUE THREAD

**Issue by CuddleBear92** [japanesemediamanager/ShokoDesktop#186]
maybe we should setup a https://www.transifex.com/ page for translations of the programs, would love to help out doing it in Norwegian, Swedish and maybe Danish.
i wouldn't use it myself (using the program in another language) but i can see alot of people might have good use for it, ofc with a site like that you can let people translate the program into anything you want really. 
cost by the site aswell as other server costs can be handled by Patron for example, tho i dont know how many actually use your program ATM (as very few comment at all)

**Comment by jmediamanager** [comment]
Looks good but not free?

**Comment by AreFinstad** [comment]
sadly not :/ 

not sure if there is anything like it around for languages.
i mean, anime is something that is shared around the world.
people that speak all kinds of languages might have a use for it, even more once they support their mother tongue.

im really thinking about all the Germans and South Americans here (where they dont use English as much as we do at all and they have subs and dubs in theirs language already)


but too be fair, its not really expensive at all really..... would pay for it myself, but atlass im a NEET ATM :( 

but small sums like Patron might be in order tho, it can help out with this, the server costs and any other costs you might have to support this project. (it is also free to sign up for one)

**Comment by jmediamanager** [comment]
Yeah I'd prefer not to ask for money from anyone, unless it gets too expensive.

**Comment by AreFinstad** [comment]
well i wouldn't say Patron is asking for money, i would say its more like sharing the load. a few Dollars/Euros/Pounds here and there from a large amount of people isnt much at all, but it does prob pay the bills and more. 

if there really is alot of people using the program already, why not just sign up and see how it goes. if there isnt much traffic for it then why not?

**Comment by ElementalCrisis** [comment]
Adding Help Wanted label, anyone who would like to translate JMM into another language please contact me on Discord.
