### ISSUE TITLE
Feedback When Submitting TvDB/The Movie DB Links

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoDesktop#205]
So while going through and linking all my series that currently don't have a TvDB or The Movie DB link I can't help but feel like I've done some of these before. My settings have always been set to Get everything and Send everything so it leaves me to think that my previously submitted links were not approved. I think a good feature would be some sort of notification system when your submitted link was approved and if denied then the reason why. Additionally the ability to reply would also be beneficial because what if the person reviewing submissions was mistaken and denied it when in actuality it was correct.

**Comment by AreFinstad** [comment]
making the reviewer comment on each review he does takes up time. i already think the UI is already cluttered enough. if anything we need it more streamlined.

there is also a fix for you already in JMM, under the Utilities tab there is a new Community Data tab. in that tab you can sort all your series after whats not correct with the approved links and alot more, you should really try it out.

here is the Download Link (its a Beta so there may be Bugs everywhere, and should only be used if you are willing to try)

https://github.com/japanesemediamanager/jmmserver/issues/116
"For those interested in trying out the beta, you can download it here
http://www.jmediamanager.org/latestdownloads/beta/JMM_Beta_3.4.4.1.zip

And here is some information on the changes
http://japanesemediamanager.github.io/changes/3.4.4/changes344.html "

**Comment by AreFinstad** [comment]
other thoughts about this, Admin/Creator prob got some plans of feedback as in the Community Review Tab there is a Stats page that isnt used yet (not yet added in).
i guess we can see the stats of each mod and see their success rate and so on. 
maybe he can open up that side of it to the public and let people agree with the choices the mod makes and so on.

**Comment by AreFinstad** [comment]
also note, that there is over 1900 series that is on the review list of tvdb..... and ATM i think im the only one that does this, atleast in the last 2-3 days. was up to around 2300 and i have worked it down to around 1900 soon and im still going.
wish i could do it faster, but with the way UI is and the Error pup-ups its hard to be willing to do it, once its gets smoother and easier to use it will go alot faster. and ofc once the list is worked down, all new series will be reviewed right away on release and so on whenever you guys link it the first time.

**Comment by AreFinstad** [comment]
yeah got down to around 1800 series left in the list...... only to get banned AniDB of excessive usage, i think we need JMM to track how many sites we open in each hour so we dont get banned (i know its might be anything from 15min-24hours but its still an issue IMO.).

**Comment by ElementalCrisis** [comment]
I'd say only feedback needed only if denied. With a giant list like you were saying maybe you could select a reason and that's what the user would get. So if they linked it wrong you would select linked wrong and they would get that message and could see that they had linked it wrong.

**Comment by AreFinstad** [comment]
well manual linking in the review process fixes that mostly, if the reviewer takes his time to do so. i know i would.
i have also already made an issue about declining and/or skipping approvals
https://github.com/japanesemediamanager/jmmclient/issues/199

**Comment by ElementalCrisis** [comment]
Here's an interesting case. While going through and fixing any missing TvDB / The Movie DB for my series I came across this anime, http://anidb.net/perl-bin/animedb.pl?show=anime&aid=8976. 

![jmmd - series linking](https://cloud.githubusercontent.com/assets/9443295/9432762/c226a12c-49dc-11e5-84f4-447df007c5f4.png)

As you can see in JMMD there is no English link for the series "X" yet when you click the TvDB link you're taken to http://thetvdb.com/?tab=series&id=70865 which is in fact the English link for the series. Would something like this be denied simply because I used the first link, which is apparently for the German version?

**Comment by AreFinstad** [comment]
you cant find it there for some reason, but if you do check the settings on tvdb its does have and English setting, and i would approve of that link aslong as the episode names are in English.
feel free to edit and change things on the tvdb pages as its free to edit those, if its locked then you can just ask on the forums and people most of the time get back at you within a day to open the series up for you. 

i am banned from the AniDB site ATM for overusage of the new review program...... so is it correct that AniDB ID 8976 is S0E2 in TVDB as you have shared? (unsure if this is an old one)

**Comment by AreFinstad** [comment]
also to note, that TVDB does share the same ID across languages (IF its added correctly) so if you double check the ID on the website and sees its English then its fine to use whatever language....... i think (plz comment on this if im wrong here)

**Comment by ElementalCrisis** [comment]
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=8976 is an OVA that is both a prequel and summary of the TV Show. TvDB has it listed under specials as episode 2, episode 1 is X The Movie (http://anidb.net/perl-bin/animedb.pl?show=anime&aid=429) though it seems the episode ordering does not really apply for specials.  

I usually make edits on TvDB when something doesn't show up in JMMD.

**Comment by AreFinstad** [comment]
approved both of them.
i would rather not do more approvals for a day or so till i get unbanned..... as i can't open any AniDB pages to read info and so on.

**Comment by ElementalCrisis** [comment]
No worries, thanks for approving those.

**Comment by AreFinstad** [comment]
yeah, i would approve all of them if i could.... now i cant even view web pages on AniDB.
the thing is with how it is ATM is that there is a random series button and i just press that whenever im done reviewing one. since the list is so huge and there is no other way that just pressing random i got no choice in what i actually review, unless i know the ID's.
would be nice if we had a way to get the newest series first or the once with most users having.

**Comment by jmediamanager** [comment]
Yup I will try and make this whole thing a bit more user friendly, just keep in mind that it is a work in progress.

@ElementalCrisis let me know if you would like access to the Community side of things, and I will give you access, as I need people who are quite active.

I would like to do more linking stuff as well, especially to sites like ShanaProject etc

**Comment by AreFinstad** [comment]
@ShanaProject YEEEEES! i would love that!
Hummingbird is also a good thought of supporting as its a nice site for talking about shows and such.

**Comment by ElementalCrisis** [comment]
Sure, I wouldn't mind helping out. 

Is ShanaProject like Nyaa?

**Comment by jmediamanager** [comment]
Yes, a little bit
http://www.shanaproject.com/

You can follow the shows you are interested in and set up RSS feeds for your torrent client.
I use it mostly for getting BD versions of the shows I want.

Just drop me a mail at jmediamanager@gmail.com, and we'll get access sorted out.
If you feel like it is too much work for you I can just remove you later.
Not expecting everyone to put in as much effort as @AreFinstad  does ;)

**Comment by AreFinstad** [comment]
Shana is Torrent RSS feeds of tokyotosho (which also contain Nyaa) its a great site if you are watching a show that is not done yet as you will auto download all the episodes of your choice when they are released. 

with JMM support we should be able to sub/follow a show to add it our RSS feed and so on.

**Comment by AreFinstad** [comment]
much effort? meh, have too much time on my hand and i like doing it while watching my Youtubes...... not that i have actually watched any Anime in months XD

**Comment by ShanaProject** [comment]
You rang? Let me know if we can do anything on our end that would be any help.

There's been some requests on our bitbucket page asking for API's and stuff...

**Comment by AreFinstad** [comment]
oh im sorry, was kinda just replying to working in Shanaproject into JMM and not actually calling you.... so sorry, if you are indeed the creator of Shana and got something that might help then feel free to do so.
i feel JMM and Shana would work great together as JMM uses downloaded files that Shana links too and so on.

**Comment by jmediamanager** [comment]
Hi @ShanaProject, an API would definitely be awesome
I found this issue on your BitBucket page
https://bitbucket.org/shanaproject/shana-project/issues/76/please-provide-an-api-for-accessing

The part I am planning on doing is the mapping from AniDB to ShanaProject series.
As a secondary option I would also do mapping from AniDB groups to groups in ShanaProject, I'm not sure if you store this in your database.

NOTE - There are other sites out there which also do mapping between different community sites

Let me know the best thread to reply on your API changes, and I will make my comments on what I think your API would need ;)

Regardless I will still be doing support for ShanaProject as I am an avid user myself, and linking to the webpages is better than nothing.

**Comment by ShanaProject** [comment]
That thread or this thread, or via email (taiga.anime@gmail.com). Biggest limitation is time to implement stuff, since I get very little time to work on SP anymore =(

**Comment by jmediamanager** [comment]
Yup I can understand that for sure :)

I'll post on the BitBucket thread
