### ISSUE TITLE
Add button to remove missing file from database

### ISSUE THREAD

**Issue by anzerman** [japanesemediamanager/ShokoDesktop#261]
Would be good if there was a button shown in JMMdesktop to remove an episode entry that no longer has a file available. I realise there is an option on the server, however would be a nice to have for the desktop client too :)

**Comment by AreFinstad** [comment]
actually you do have it in JMMD in the server tab, no need to swap program to do that.
but you could say you wanted it in the series page as you said on Discord.

**Comment by ElementalCrisis** [comment]
I know it's been talked about before in regards to organizing the available options a little better and will hopefully happen whenever JMM gets a redesign.

**Comment by da3dsoul** [comment]
You can now hit delete and it will remove individual files, or remove missing files to remove them all.
