### ISSUE TITLE
Local path not accesible with password protection

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoDesktop#268]
When adding SMB shear in local path:
\netbios-name\drive\folder 
It is not posible to enter it when its need authorization.
Because JMMClient run as Administrator it wont use the login/pass combo from current user and there is no popup for adding login/password for it.

**Comment by craige1** [comment]
The run as admin requirement has been removed, and hopefully should see the light of day in the next release. This should help with this issue.

**Comment by bigretromike** [comment]
This is reeeeeeaaallyyy GREAT NEWS! Thanks
