### ISSUE TITLE
AVDump issue

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoDesktop#269]
I added file from Unrecognized by clicking on button AVDump

Function OpenClipboard not responding (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN)

![clipboard02](https://cloud.githubusercontent.com/assets/6052025/11572446/a46c8910-9a01-11e5-8aa5-9cde27eb2a35.png)

**Comment by AreFinstad** [comment]
this is not 100% consistent most of the time, happens randomly for me it seems at times.
i know you can push past it to still get the copy to clipboard action you need.

**Comment by bigretromike** [comment]
So maybe there should be a try { } catch { } just to not scare people out ?:-)

**Comment by bigretromike** [comment]
Im getting this error more and more, "Manual linked" im clicking AVDump there, and click on the newly added record in AniDb AV Dump.
But when I click on something else and the again on the newly added record it work ok.

**Comment by AreFinstad** [comment]
yeah, thats what is so weird with this bug. its only happens sometimes and not always and it can happen at one point while if you try again in less than a min it will work fine. its really weird and slows down the workflow when using the AvDump tool.

**Comment by bigretromike** [comment]
It looks like it try to copy something that aint present there . like he reffer to object that is not YET created. Thats why when you refresh it it get create and probably not want to copy it to clip anymore anyway.

**Comment by da3dsoul** [comment]
I haven't heard of this recently (in a year). I'll close this for now, and it can be reopened if needed
