### ISSUE TITLE
AnimeBytes search results missing season/episode number

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [japanesemediamanager/ShokoDesktop#299]
Currently an AnimeBytes search returns the showname/quality/subbing group of a torrent, but misses the episode number. This makes it quite hard to identify what episode a torrent is.

![dsueg0c 1](https://cloud.githubusercontent.com/assets/5640470/13373889/d7627298-dd73-11e5-8097-0ca5a4ba0535.png)

My request is to have the episode or season number added to the results

**Comment by ElementalCrisis** [comment]
Torrent functions have been removed.
