### ISSUE TITLE
Only count an episode as Missing if it has Aired

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoDesktop#315]
I'll just use Seisen Cerberus as an example, but it has info on aniDB for 4 episodes, two of which have not aired. JMM counts the unaired episodes as Missing, even though it's not logical to have them.

**Comment by da3dsoul** [comment]
Okay, it updated when I opened it. It seems I have quite a few series that show missing files, even though they are not missing.

**Comment by ElementalCrisis** [comment]
Check for Unrecognized Files under Utilities and see if some of the episodes show up there. Otherwise try running Update All Stats and see if that fixes it. If that doesn't fix its possible the files were not hashed. Post some examples of files you have that are not showing up.

**Comment by da3dsoul** [comment]
Yeah, I'm running scans right now. It's possibly related to #308 and #297

**Comment by jmediamanager** [comment]
Just to clarify, it already works as you described in the title.

There are tow types of missing indicators in JMM Desktop
- Yellow ! - means you are missing an episode that has aired
- Red! - means you are missing an episode that has aired and is by one of the groups you are collecting files from.

Yes this is just an issue with the way that the stats are calculated.
When you first import a series,, it doesn't have all the information it needs to accurately calculate the missing episode stats.

It does these stats on a lower priority, and they should get updated eventually.

Restarting JMM Server will also re-calculate these cached statistics.
