### ISSUE TITLE
Remove extraneous groups from filters with multiple conditions applied to series

### ISSUE THREAD

**Issue by naarcissus** [japanesemediamanager/ShokoDesktop#317]
![screenshot - 2016-04-14 22_58_15-jmm desktop](https://cloud.githubusercontent.com/assets/3468111/14552672/3aba9d52-0295-11e6-8f39-0d13428240fd.png)

**Comment by ElementalCrisis** [comment]
I wonder if it has to do with filter order. Try rearranging the filter and see if they still show up.

**Comment by naarcissus** [comment]
I tried rearranging the **Filter Conditions**.

1. [Not In] aX:XXX (hentai)
2. [In] aC:Named (chapters with names. makes for easy skipping of OP/ED/Pre.)
3. [In] aAL:English (audio language: english)

and

1. [In] aAL:English
2. [Not In] aX:XXX (hentai)
3. [In] aC:Named

Groups for which no series matched conditions were still included.
Also, messed with **Sorting** order, in case you meant that, no effect.

**Comment by naarcissus** [comment]
Further illustration:

This season has "aAL:English":
![screenshot - 2016-05-20 07_49_46-jmm desktop](https://cloud.githubusercontent.com/assets/3468111/15432341/b28d97ce-1e62-11e6-9018-b57462d1a664.png)

This Season has "aC:Named"
![screenshot - 2016-05-20 07_50_38-jmm desktop](https://cloud.githubusercontent.com/assets/3468111/15432368/c6c4b290-1e62-11e6-978d-4eb38e8383b6.png)

Filter Settings- Include series with both "aAL:English" and "aC:Named":
![screenshot - 2016-05-20 07_52_24-jmm desktop](https://cloud.githubusercontent.com/assets/3468111/15432429/13829e76-1e63-11e6-88d8-ea407e754dbd.png)

Result:
![screenshot - 2016-05-20 07_54_16-jmm desktop](https://cloud.githubusercontent.com/assets/3468111/15432449/24682c4c-1e63-11e6-8cbd-2bb42ee6e05f.png)

**Comment by da3dsoul** [comment]
I think this is fixed
