### ISSUE TITLE
Codec in Renamer for manually linked files

### ISSUE THREAD

**Issue by naarcissus** [japanesemediamanager/ShokoDesktop#318]
When renaming manually linked media files:
- **Video Bit Depth**(**Z**, **%bit**) is available.
- **Video Resolution**(**W**, **U**, **%res**) is available.
  But
- **Video Codec**(**C**, **%vid**) is unavailable.
- **Audio Codec**(**J**, **%aud**) is unavailable.

Seems to me that if **%bit** information is available to JMM, *** Codec** could/would/should be too.

Further, lol, things like Duration, Bit Rate, FPS, Display Aspect Ratio, Scan Type, Audio and Subtitle Language, etc. are provided by _MediaInfo_ as well and could be available. Though I understand the number of tests is limited in current format. :neutral_face:

**Comment by da3dsoul** [comment]
If you view the file in the episode menu, the codec info is there as well. May be related to https://github.com/japanesemediamanager/jmmserver/issues/245

**Comment by da3dsoul** [comment]
Fixed
