### ISSUE TITLE
Delete torrent before moving from drop source

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoDesktop#320]
The drop source and destination is a great feature. Unfortunately, when it moves files, it will either fail because the file is in use, or cause the torrent to be a waste of RAM in its invalid state. This would probably be annoying to program, as the torrent handling is done is JMM desktop and moving in server, but it would be nice to have some means of cleaning up.

**Comment by ElementalCrisis** [comment]
Torrent functions have been removed.
