### ISSUE TITLE
[Improvement?] BakaBT search

### ISSUE THREAD

**Issue by Rand-Random** [japanesemediamanager/ShokoDesktop#337]
Hi.

Not sure if its the correct place to ask the question, since its not really an issue more a simple question.

I regulary download complete series from BakaBT and found it difficult to check if I already have the series or not, since my memory isnt that great I just couldnt tell and had to search JMM again and again.

So I kinda got annoyed doing that and wrote a little (external) tool that does the job for me.
It takes a search query from BakaBT in my case I was looking for BluRay Release I dont have, so I used the query:

https://bakabt.me/browse.php?only=0&hentai=1&incomplete=1&lossless=1&hd=1&multiaudio=1&bonus=1&c1=1&reorder=1&q=bluray

In the resulting HTML Document, I search for all entries and check the page for example:
https://bakabt.me/torrent/162318/11eyes-bd-720p-aac-ftv-wasurenai

In that HTML Document I go and search for the anidb.net - Anime ID and check if the JMM Server already has a reference to that Anime ID.

After parsing all pages and all entries from the query, I output them in a CSV file looking like this:

```
AniDb_ID;Url;Download Url;Exists
9749;https://bakabt.me/torrent/344597/grisaia-no-kajitsu-bd-1080p-shujinowski;https://bakabt.me/download/344597/1462495211/4f8a1ce6647891c19aa8dac63e98a604/1406925/grisaia-no-kajitsu-bd-1080p-shujinowski.torrent;True
4897;https://bakabt.me/torrent/183702/baccano-bd-720p-coalgirls;https://bakabt.me/download/183702/1462495211/a570b88d3152326430ff41ee3f305bdc/1406925/baccano-bd-720p-coalgirls.torrent;False
```

You could input any search query, for example categories like ecchi, fantasy, action... and check if there is a show that you are missing.

Now my question is if this feature is something thats usefull not only for me or not, and if its worth integrating into JMM Client?!?

Feedback is welcome.

(_pray to god that such a feature does not already exists and I simply missed it_)

**Comment by ElementalCrisis** [comment]
Well there is the series match window at the bottom. Im sure something could be added that states you already have the series. What do you think @jmediamanager?

**Comment by da3dsoul** [comment]
If you click on something, it'll tell you what episodes you have.

**Comment by Rand-Random** [comment]
@ElementalCrisis cant seem to find the "series match window" you are talking about.

**Comment by da3dsoul** [comment]
![screenie](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/Screenshot%202016-05-06%2003.48.13.png)

**Comment by Rand-Random** [comment]
@da3dsoul seems like you didnt quite get the point I have tried to make, I know that you can check JMM Desktop if the series exists and what episodes you have, BUT
thats exactly what I DO NOT want to do.

Lets assume the above mentioned query
(https://bakabt.me/browse.php?only=0&hentai=1&incomplete=1&lossless=1&hd=1&multiaudio=1&bonus=1&c1=1&reorder=1&q=bluray)

This query results in 373 anime series, so I would need to manually check all those 373 anime series if I already have them by searching JMM Desktop manually, and thats where my tool steps in you pass it a query like the one mentioned and it automatically tells you which of the found series you have or have not and than you can download them.

**Comment by da3dsoul** [comment]
Hmmm, tag search and hide anything you have? That'd be pretty nice.

**Comment by da3dsoul** [comment]
I see what you mean

**Comment by ElementalCrisis** [comment]
Oh OK, so an indicator in the results informing you that you already have the series. I like that idea.

**Comment by Rand-Random** [comment]
Here is my tool that I wrote and used for this job. (Source Code included)
[BakaBT.zip](https://github.com/japanesemediamanager/jmmclient/files/253898/BakaBT.zip)
(I used the BakaBT.WebClientEx, the BakaBT.Utils.DownloadWebPage, BakaBT.Program.Login/ValidateCookie from jmmclient)

As I said its an external tool and doesnt communicate with JMM Server in anyway.
it goes straight to the database and does the SQL query directly to it, so you have to enter the credentials for the SQL Server aswell for BakaBT.

If asked the serach query for bakabt, open bakabt in any webbrowser search for something and copy/paste the URL into the application. 

(The application isnt really failure free, since I only wrote it for myself and didnt initially plan to release it in anyway)

**Comment by ElementalCrisis** [comment]
Thanks for sharing! I use MySQL so I can't use the tool but I would very much like to see this feature implemented.

**Comment by da3dsoul** [comment]
No it still helps plenty. The schema style is similar

**Comment by da3dsoul** [comment]
Downloads are likely to be removed in the next few days. I'm going to closed this, and it can be reopened if it once again becomes applicable.
