### ISSUE TITLE
Series selection for renaming adds some files twice

### ISSUE THREAD

**Issue by SL-Gundam** [japanesemediamanager/ShokoDesktop#445]
If use the series selection for renaming and i select a series with files that span multiple episodes (according to JMM) it adds all the files in question twice to the preview list

See my screenshots
![normal_entire collection](https://cloud.githubusercontent.com/assets/912973/18225423/422f5642-71f1-11e6-84bb-314b291adcac.png)
![series_files added twice](https://cloud.githubusercontent.com/assets/912973/18225422/422ad7fc-71f1-11e6-834f-8dcf07c9211a.png)

**Comment by da3dsoul** [comment]
Mk, it's minor but I'll fix it

**Comment by da3dsoul** [comment]
Right I was going to fix this
