### ISSUE TITLE
Error using Anidb AV Dump

### ISSUE THREAD

**Issue by nicoenma** [japanesemediamanager/ShokoDesktop#450]
I'm getting this error with the new version of JMM Desktop when dumping files.

"Testing communication with AniDB
Format Error: Could not parse Id; Check for program updates.
Pending AniDB reply timed out"

**Comment by mmuffins** [comment]
This might actually unrelated to jmm. I tried parsing a few files with avdump (the standalone executable, not from within jmm) and got the same timeouts. Eventually it finished but sending the scan results to anidb took forever.

**Comment by VadAbel** [comment]
The error can come from the file : Ionic.Zip.Reduced.dll
The version between avdump archive and JMM Desktop is different .
With the file from avdump archive, I don't have any problem.
![capture2](https://cloud.githubusercontent.com/assets/22178832/18492149/0c80fcc8-7a0a-11e6-8ee9-c6731bb3032f.png)

**Comment by da3dsoul** [comment]
AV dump isn't supposed to come with desktop.... So yeah, it's the wrong version

**Comment by ElementalCrisis** [comment]
Did a quick look and I don't see it being used in JMM Desktop, can you double-check @da3dsoul?

**Comment by da3dsoul** [comment]
It works for me. The installer I have didn't come with it

**Comment by hidden4003** [comment]
It is related to mediainfo.dll updated in latest release

**Comment by ElementalCrisis** [comment]
Do we uses the updated version?

**Comment by da3dsoul** [comment]
This is fixed I believe
