### ISSUE TITLE
Update Client to Use nancyfx Only

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoDesktop#472]
JMM Desktop can either be moved to the /api prefix and we can expand it as needed, or we need to port the servicehosts to nancyfx.
[] JMMServerBinary
[] JMMServerImage

People may edit this to add other necessary changes.

**Comment by bigretromike** [comment]
- [x] JMMServerImage WCF usage was moved to JMMServerImage2 (Legacy Nancy)

I didn't remove core of clientImage to easier come back in case needed - It will be done probable on cleaning or moving Binnary Blob Service to Nancy /bin/

**Comment by hidden4003** [comment]
This change is supposed to happen on a nancy branch not on master branch.

**Comment by bigretromike** [comment]
Didnt know, sorry 

On October 7, 2016 10:21:23 AM GMT+02:00, hidden4003 <notifications@github.com> wrote:
>This change is supposed to happen on a nancy branch not on master
>branch.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmclient/issues/472#issuecomment-252180931

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
Also i didnt know i merge pr to client ;-)

On October 7, 2016 10:21:23 AM GMT+02:00, hidden4003 <notifications@github.com> wrote:
>This change is supposed to happen on a nancy branch not on master
>branch.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmclient/issues/472#issuecomment-252180931

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
