### ISSUE TITLE
TvDB link in Series entry gets removed when modified

### ISSUE THREAD

**Issue by DerRM** [japanesemediamanager/ShokoDesktop#480]
If I try to modify for example the starting episode from where the Episode Information should start to be used the complete link to the TvDB gets removed and it's also not possible to relink the series after that.

**Comment by ElementalCrisis** [comment]
Can you post your log?

I was able to remove an existing link and re-add it without problem.

**Comment by DerRM** [comment]
Log: [2016-10-09.txt](https://github.com/japanesemediamanager/jmmclient/files/518566/2016-10-09.txt)

For some reason now it seems to be working but it still remains that if I modify the link for the TvDB it gets removed but after a manual refresh the information is now correctly shown.

After changing the starting episode
![screen1](https://cloud.githubusercontent.com/assets/870059/19223816/23dc7478-8e79-11e6-84a1-73dfa75dfca7.png)

After manual refresh:
![screen2](https://cloud.githubusercontent.com/assets/870059/19223815/23db6376-8e79-11e6-9abe-ad2c616ed1fc.png)

**Comment by ElementalCrisis** [comment]
Ah right, that's normal.

If you update the TvDB link, it removes the old link and adds the new one. JMM does not update in real-time so you only see the removal, once you refresh you see the newly added link.

**Comment by da3dsoul** [comment]
It also operates on the queue. Unless we lock up the ui for a long time until it finishes, it not fixable. Maybe something that will be fixed in the queue factory
