### ISSUE TITLE
unrecognized sorting sorts by starting number instead of size

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoDesktop#485]
as the title says, unrecognized sorting sorts by starting number instead of size.
so starts on 0 or 9 and goes up and down on per number instead of the total number value. 
didnt check the live version.

![](http://i.imgur.com/36p9Fer.png)

**Comment by da3dsoul** [comment]
Oh wow, it's sorting by string.

**Comment by da3dsoul** [comment]
Can someone with unrecognized files test this on latest commit? I don't have any, but I think I fixed it

**Comment by ElementalCrisis** [comment]
There was a similar issue in Downloads awhile back that Rand fixed. It's possible the same error is present in all the utilities.

**Comment by da3dsoul** [comment]
I've been adding natural sorting to them all, that;s why I say

**Comment by ElementalCrisis** [comment]
Can confirm it's fixed.
