### ISSUE TITLE
tvdb linking does not save correctly (3.7.0.126)

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoDesktop#487]
seems the tvdb links does not save correctly.
for example on hunter x hunter there is 3 seasons on tvdb. 
its admin confirmed and everything.
if i choose to use the community recommendations it has saved a few ways.
linking episode 59 to season 3 instead of 2 and not saving the season 1 link at all
i have also had episode 59 be linked to season 2 and episode 79 to season 3 (which i dont even find in the community tab)

it really seems random in many ways with what i get and dont get when using the premade links of the community.

unsure if manual linking outside of the community links works 100% aswell.
seems weird comparing too how it was.

tried +5 times and it didnt get it right once.

**Comment by da3dsoul** [comment]
Manual linking works (I made sure with @baine's help testing). I'll need to look at linking community recommendations for larger shows.

**Comment by da3dsoul** [comment]
For noting, if an episode that is considered a special or OVA on TvDB/AniDB but not the other, it will throw off the count and link all episodes after incorrectly

**Comment by da3dsoul** [comment]
Try this again on latest for me. @ElementalCrisis said it's working for him

**Comment by da3dsoul** [comment]
Closing this. Reopen if it's still applicable
