### ISSUE TITLE
Can't remove filter conditions in group filters

### ISSUE THREAD

**Issue by RickDB** [japanesemediamanager/ShokoDesktop#493]
**Issue**

In group filter edit mode when pressing the remove (X button) it will show dialog asking for removal however afters filter remains.

**To reproduce**

Edit group with filter and add filter condition like tag, now try to remove it and will remain in place.

**Comment by RickDB** [comment]
So far found 2 bugs with this:

- NiceDescription doesn't return the actual tag / description but instead the condition type ("Include in" for instance) :

https://github.com/japanesemediamanager/ShokoClient/blob/master/JMMClient/MainWindow.xaml.cs#L2495

You will notice this right away  in the yes / no remove dialog as instead of the actual tag you will get the condition type instead.

- Now for the actual cause of of this issue is that the gfc.GroupFilterID is always 0 during testing here:

https://github.com/japanesemediamanager/ShokoClient/blob/master/JMMClient/MainWindow.xaml.cs#L2495

So will never result in any matches and leave the filter condition in there.

**Comment by da3dsoul** [comment]
Moving this to 3.7 milestone, it's important and shouldn't be too annoying to fix

**Comment by da3dsoul** [comment]
I'm unassigning myself. hopefully @maxpiva can get to it

**Comment by ElementalCrisis** [comment]
@RickDB can you check to see if this is still an issue for you? I was able to delete multiple groups without issue.

**Comment by da3dsoul** [comment]
This was fixed. It has a different issue now, but once it's fixed it will be done. I'm closing this as it will be done before 3.7.5.0 is released
