### ISSUE TITLE
trakt manual searching cant find season or episode number. cant link at all.

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoDesktop#496]
every time i try to manually link a trakt link to a group this happens.
![](http://i.imgur.com/RDHG1yy.png)

and because i cant choose a season or episode number i cant link it either.

**Comment by Stonedestroyer** [comment]
Related to https://github.com/japanesemediamanager/ShokoServer/issues/512 possibly.

**Comment by AreFinstad** [comment]
this seems to only happen with groups that dont have a link at all saved locally. 
if a link had been made somehow already then it shows up it seems.
even deleting all the trakt links from a group and readding them is not an issue. 

this seems to happen to every group i have. either it doesnt work or it just works when it has a link already.

**Comment by RickDB** [comment]
Checked a few groups here with or without Trakt info but can't get it to show that error, did add a fix just now (#512) for episode lookups but pretty sure it's unrelated to this.

**Comment by ElementalCrisis** [comment]
Closing, @AreFinstad please reopen if this is still an issue.
