### ISSUE TITLE
File Rename - Recently Added

### ISSUE THREAD

**Issue by Remnence** [japanesemediamanager/ShokoDesktop#508]
Please add the ability to rename #xx recently added episodes in the drop down menu for the rename utility.

**Comment by da3dsoul** [comment]
As in the ability to fill the list with the last [number] files added?

**Comment by Remnence** [comment]
@da3dsoul Exactly that. The most common use I have for the renamer is recent episodes that anidb hashes quickly but doesnt have an episode title for. I then have to go back and rename entire series to fix that when anidb updates a few days later.

**Comment by da3dsoul** [comment]
That's fair and doable

**Comment by da3dsoul** [comment]
Right I was going to do this. I'll fit it into the next release.

**Comment by da3dsoul** [comment]
Almost done
