### ISSUE TITLE
Continue Watching Filter displaying wrong series

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/ShokoDesktop#511]
I am currently watching Handa-kun (11908)
However the continue watching filter shows Barakamon (10111) instead.
The series are related but I haven't watched any episodes of Barakamon

**Comment by da3dsoul** [comment]
Press the update all stats button

**Comment by da3dsoul** [comment]
IDR, the part that regenerates group filters might only be in dailies
