### ISSUE TITLE
Cleaning Multiple in groups, delete all should only delete duplicated files

### ISSUE THREAD

**Issue by Animeimp** [japanesemediamanager/ShokoDesktop#512]
When cleaning with the Show Multiples, the delete all button on a group entry should only delete the files that are duplicated, leaving any files that were not a match in the Multiple.

i.e.
Some Anime has the following files.
  Group1: episodes 1-10,12
  Group2: episodes 6-12

The Delete all button (or a new button) should only get rid of Group2 episodes 6-10, 12 - leaving episode 11 since that is currently the only file for episode 11.

Especially on older anime, I have to grab episodes from various groups in order to complete the series.

**Comment by da3dsoul** [comment]
See japanesemediamanager/shokoserver/issues/545
