### ISSUE TITLE
Suggestion: Add scrollbar or some such to long error messages.

### ISSUE THREAD

**Issue by CatmanIX** [japanesemediamanager/ShokoDesktop#517]
For example, when removing a few dozen files that don't exist anymore from the "unrecognized files" utility, the message list gets ridiculously long: 

![](http://i.imgur.com/cbeVblf.png)

You can't even hope to click on the "OK" button, not that it's a serious issue as the [X] works just as well, but it would be nice if it behaved better, just in case maybe there's a different message farther down you can't see.

**Comment by da3dsoul** [comment]
I can do this pretty quickly I think.
