### ISSUE TITLE
"Auto Link" won't stay disabled.

### ISSUE THREAD

**Issue by CatmanIX** [japanesemediamanager/ShokoDesktop#518]
![](https://i.imgur.com/9cbMVxq.gif)

As seen above, disabling auto link does not stick, and when leaving the series view into another and then back to that series, it's shown as enabled again.

I'd post logs, except there don't seem to be any of this incidence. I made this gif at 18:40, and when checking the logs, the latest lines on both server and client were at 18:32 regarding an unrelated series.

**Comment by da3dsoul** [comment]
Yeah, I don't know what that button is supposed to do, but there is no setting to disable auto linking right now. I'll self assign it and might get to it tomorrow.

**Comment by da3dsoul** [comment]
I'm removing that button in favor of a global setting to enable and disable auto linking, one for TvDB, Trakt, and MovieDB, and another for MAL. After all, that button is pointless, since it is already auto linked by the time you can see it.
