### ISSUE TITLE
Multiple Files tab wont load on enter

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoDesktop#520]
## Description

Multiple Files tab wont load on enter;
Others tabs there does load on enter, only this one is without love;

**Comment by da3dsoul** [comment]
By enter, you mean by pressing the enter/return button on the keyboard, right?

**Comment by bigretromike** [comment]
no. I mean "enter the tab" when you click on tab, and tab load its content.

**Comment by da3dsoul** [comment]
Oh I can do that in two seconds
