### ISSUE TITLE
Multiple Files - Delete all issue

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoDesktop#521]
## Description

Inside Multiple Files when using `Delete all` windows popup with files that will be deleted;
No matter how many there are files there (more than 1) if i click `confirm` but the files are somehow not accessible (missing), there is information about in in bottom of the window and it tells that it was unable to find those and remove record. The problem is that shoko only delete 1 (first) record of those files, skip rest of them and remove only 1 item from label that is next to `Delete All` button that trigger this window

**Comment by da3dsoul** [comment]
see #522

**Comment by da3dsoul** [comment]
This should be fixed. Reopen if not
