### ISSUE TITLE
Multiple Files - Open Folder

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoDesktop#522]
## Description

While using `Multiple Files` clicking on  `Open Folder` end up with:
`The file could not be found`
This is after `remove missing files` and `refresh`

Using `Delete All` (not sure for `Delete`) results in removing the file and no error
Going to folder that hold this file I can see it without problem - it's just ShokoDesktop can't open it, but can access (as it can and will delete it after pressing `Delete`)

Edit: No, Delete don't work as `Open Folder` but `Delete All` work fine.
The file contains non english characters (if that is a problem)

**Comment by da3dsoul** [comment]
It's part of a much bigger issue. It follows the same flow of thought as the hasher working, but not being able to resolve a file for moving, renaming, playing, deleting, etc.

**Comment by da3dsoul** [comment]
This should be fixed now. Reopen if not
