### ISSUE TITLE
add support for audio and sub tracks in quality ranking

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoDesktop#531]
right now the quality ranking does not list languages with audio or subs at all. 
if its the same release group then it shows as the same "quality" even if one would have another language or dualaudio. 

the quality ranking is used on the multiple files tab aswell as the file tab in Shoko Desktop. 

example: 
![](https://puu.sh/vpt4a/1779b7a802.png)

would be a bonus if they showed the language they had on their audio and subs too, not just the codec.

**Comment by da3dsoul** [comment]
a part of http://github.com/japanesemediamanager/shokoserver/issues/545
